### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by AmirHossein484** [spotify/echoprint-server#5]
Hi, I'm .net developer and I don't know much about python and java (just a week ability to read the code), I want to port this server side logic into C# and WCF, Can you explain a bit more about how to build the project? I have tried CMake to build C++ code but it gives error every time, In building the Python extension : error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1120 and ....
I want to ask you if you could explain a bit more about how to build the project step by step, Something like Codegen windows compilation instructions : 
https://github.com/spotify/echoprint-codegen/tree/master/windows

Thanks

**Comment by nicolamontecchio** [comment]
Unfortunately windows builds are not supported at the moment.

**Comment by AmirHossein484** [comment]
Hi, Thanks ..
Then, Can you please share to me the code map and the logic so I can build windows version?

**Comment by nicolamontecchio** [comment]
I'm not really sure what you mean, but the whole C library is contained in just two files, `libechoprintserver.h` and `libechoprintserver.c`. The rest is all python / java code and other convenience scripts.
