### ISSUE TITLE
there is a question, what can I do?

### ISSUE THREAD

**Issue by holens** [spotify/echoprint-server#8]
There are many of json file that use echoprint-decode to transfor in the folder ,
when I want to crate the index.bin, but not as you say index_001.bin,index002.bin .
-bash: /bin/cat:  the parameter list is too long....

it means that the cat command receives parameter  too much.and how you resolve?

**Comment by holens** [comment]
cat ... | ./echoprint-inverted-index index.bin
index.bin format is binary, see the implementation details below.

If more than 65535 songs are indexed, the output will be split into blocks with the following naming scheme:

index.bin_0000
index.bin_0001
...

but the cat command can't receives more file. how do you resolve?

**Comment by nicolamontecchio** [comment]
You might want to look into the `xargs` unix command.
That said, I'm not clear on what step in particular you're having difficulty.

**Comment by holens** [comment]
Ok. 

find . -name "*.json" |xargs -i head -q {} | jq -r '.[0].code'| echoprint-inverted-index index.bin
I did it again as above. but There is error as follow.

xargs: cannot fork: Cannot allocate memory
Killed

when I  use the command of echoprint-inverted-index  to create the index.bin library file, is there a function or parameter that I use to divide into several times ? 
I want that there is serial  inode.

**Comment by nicolamontecchio** [comment]
i think something like ` find . -name "*.json" -exec cat {} \; | jq ...` is what you are looking for
